[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ai_plays_codenames"
version = "0.1.0"
dependencies = []

[tool.setuptools]
packages = ["ai_plays_codenames"]